# Generated by Django 3.2.15 on 2022-10-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20221011_0428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place1',
            new_name='Team',
        ),
    ]
