# Generated by Django 3.2.15 on 2022-10-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_place1_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Place1',
        ),
    ]
